apiVersion: v1
kind: Service
metadata:
  name: weather-kafka
spec:
  ports:
    - port: 9092
      name: internal
      targetPort: 9092
    - port: 9094
      name: external
      targetPort: 9094
  selector:
    app: weather-kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-kafka
spec:
  selector:
    matchLabels:
      app: weather-kafka
  template:
    metadata:
      labels:
        app: weather-kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.5.0
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 9092
        - containerPort: 9094
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
        env:
        # --- CẤU HÌNH KRAFT ---
        - name: KAFKA_NODE_ID
          value: "1"
        - name: CLUSTER_ID
          value: "MkU3OEVBNTcwNTJENDM2Qk" # Giữ ID cố định như bạn yêu cầu
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        # Cấu hình Listener: 
        # - INTERNAL (9092): Cho Spark/MinIO trong cụm
        # - EXTERNAL (9094): Cho Python ở ngoài
        # - CONTROLLER (9093): Cho nội bộ Kafka quản lý cluster
        - name: KAFKA_LISTENERS
          value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://weather-kafka:9092,EXTERNAL://127.0.0.1:9094"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@127.0.0.1:9093"
        
        # --- CÁC CẤU HÌNH KHÁC TỪ FILE CỦA BẠN ---
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data"
---
