apiVersion: v1
kind: Service
metadata:
  name: weather-postgresql  
  namespace: default        
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: weather-postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-postgresql
  template:
    metadata:
      labels:
        app: weather-postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        # Cấu hình cho Database lưu kết quả dự báo
        - name: POSTGRES_DB
          value: "weather_db"
        - name: POSTGRES_USER
          value: "weather_user"
        - name: POSTGRES_PASSWORD
          value: "weather_pass"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        hostPath:
          path: /data/weather_postgres 