apiVersion: v1
kind: Service
metadata:
  name: weather-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: weather-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-redis
spec:
  selector:
    matchLabels:
      app: weather-redis
  template:
    metadata:
      labels:
        app: weather-redis
    spec:
      containers:
      - name: redis
        image: redis:7.2-alpine
        ports:
        - containerPort: 6379
        command: ["redis-server", "--appendonly", "yes"]