apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-config
data:
  CLUSTER_NAME: "test"
  CORE_CONF_fs_defaultFS: "hdfs://namenode:9000"
  # --- THÊM DÒNG NÀY VÀO ---
  HDFS_CONF_dfs_namenode_datanode_registration_ip_hostname_check: "false" 
  # -------------------------